name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21
        
    - uses: gradle/actions/setup-gradle@v3

    - name: Gradle test
      run: gradle test --show-version --no-daemon -Dkotlin_version=2.0.0 -Dkotlin_logging_version=7.0.0 -Dspring_version=3.3.1 -Dspring_dm_version=1.1.5 -Dkotlin_coroutines_version=1.9.0-RC
